### ISSUE TITLE
Wallet stopped receiving payment transactions from pool

### ISSUE THREAD

**Issue by beilpig** [loki-project/loki-gui#43]
Hi

I've been mining on http://loki-pool.com/# and all transactions have been received into wallet running on Linux until yesterday afternoon when my last two payments from pool were not received even though wallet has synced. I have tried rebooting wallet but these transactions just don't appear in transaction history! Any ideas???

**Comment by Doy-lee** [comment]
Hi,

We've released updated binaries that should be compatible with the new daemons that have been rolling out. Please give it a try at the release pages (linked below). Some pools started mining a different chain on the network causing some blocks and payments to be inaccurate for some time.

https://github.com/loki-project/loki-gui/releases/tag/1.0.0-rc

**Comment by newmzy** [comment]
I have had the same problem, I can use the block explorer, put in my payment address and private view key and see the outputs, but the payments (only about 8 Loki so far) haven't reached my loki-gui-win64-v0.2.0 wallet. I will install the new release and see what happens, but if some pools have been "mining on a different chain" does this mean those coins are lost?
Is it possible to let us know which pool operators have been notified so we can use them preferentially? I have seen the same phenomenon on at least 2 different pools.

**Comment by KeeJef** [comment]
I believe in the GUI settings there a rescan blockchain button

**Comment by newmzy** [comment]
> 
> 
> I believe in the GUI settings there a rescan blockchain button

Well yes, in the wallet tab of the settings there is a button which says "Rescan Wallet Balance - use this feature if you think the shown balance is not accurate".

If I click on that button it returns "successfully scanned spent outputs" but it takes less than a second so it wasn't like any blockchain rescan I have ever seen and the balance is still wrong. There isn't any problem with "outputs" as I have never sent any Loki, the problem is with inputs since these are Loki that I GPU mined on 2 different pools. Like I said, if I use a remote node my balance is correct as far as I can tell - I even received a small amount from cryptoknight.cc, the supposedly "bad" pool.
If I stop my local node, then click on remote node, it syncs around 400 blocks and then my balance is correct. I don't know enough about this to know if it is referring to my local chain and just using the remote node to "catch up". Anyway, if there is a way to get the wallet to actually scan the whole chain, not just any outputs or whatever, I would appreciate any suggestions.

**Comment by KeeJef** [comment]
this may be of assistance, Loki uses the same storage structures as Monero https://monero.stackexchange.com/questions/3122/how-do-i-delete-the-wallet-cache/3123

**Comment by Doy-lee** [comment]
You should let the daemon sync the remainder of the chain locally, switching to remote node and syncing 400 blocks seems to suggest you are not. Then afterwards, rescan on your copy of the chain. You may optionally tweak the starting scan height in the info section, the option is "Wallet Creation Height" which is the height the rescan starts from.

I recommend starting the daemon separately so you can confirm yourself it's synced and on the right chain (which can be confirmed by looking at lokiblocks.com or explorer.loki-pool.com) . Then, rescanning after confirming.
